# -*- coding: utf-8 -*-
"""Build caly_friends_new_episodes.json with 30 new Caly and Friends episodes."""

EPISODES = [
    # --- BABY (Pip) script_num 12-16 ---
    {
        "id": "pip_soft_breeze_long",
        "band": "baby",
        "title": "Pip and the Soft Breeze",
        "friend": "Pip",
        "script_num": 12,
        "lesson": "God's gentle touch is everywhere you feel safe.",
        "christian": "Psalm 23:2 - green pastures and quiet waters",
        "acts": [
            ("Welcome", "1-8", "Caly Seed hello, meadow breeze, Pip ears twitch"),
            ("Feel the breeze", "9-20", "Leaf dance, soft whoosh sounds, caregiver mirror"),
            ("Peek and sway", "21-32", "Pip hides in grass, breeze reveals, giggle loop"),
            ("Rest", "33-40", "Elder Oak shade, slow breath with breeze"),
            ("Blessing", "41-50", "Gentle lullaby, bye-bye wave in the wind"),
        ],
        "key_scenes": [
            ("Mint meadow, leaves sway, Caly Seed waves", "Hello, little one. Feel the soft breeze."),
            ("Pip bunny ears lift, grass rustles", "I'm Pip! The breeze tickles my nose."),
            ("Elder Oak branches move gently", "Elder Oak says God made gentle things for us."),
            ("Caregiver hand sways like a leaf", "Your grown-up can sway with you."),
            ("Pip spins in a leaf circle", "Round and round. You are safe and loved."),
            ("Slow breath animation, breeze calms", "In and out. Rest in God's gentle care."),
            ("All friends wave as breeze fades", "Bye-bye, friend. You are wonderfully made."),
        ],
        "chapters": "~60s, ~150s, ~240s: sway with breeze, peek in grass, gentle breath",
        "beats": [
            ("Hello, little one. Feel the soft breeze.", "welcome"),
            ("I'm Pip! The breeze tickles my nose.", "friend"),
            ("Elder Oak says God made gentle things for us.", "mentor"),
            ("Your grown-up can sway with you.", "caregiver"),
            ("Round and round. You are safe and loved.", "play"),
            ("In and out. Rest in God's gentle care.", "rest"),
            ("Bye-bye, friend. You are wonderfully made.", "farewell"),
        ],
    },
    {
        "id": "pip_moonlight_snuggle_long",
        "band": "baby",
        "title": "Pip's Moonlight Snuggle",
        "friend": "Pip",
        "script_num": 13,
        "lesson": "You are held in love even when the day grows quiet.",
        "christian": "Psalm 4:8 - peace to lie down in safety",
        "acts": [
            ("Twilight hello", "1-8", "Moon rises, Caly Seed soft glow, Pip yawns"),
            ("Star peek", "9-20", "Twinkle sounds, hide behind cloud, reveal"),
            ("Snuggle nest", "21-32", "Soft blanket burrow, caregiver cuddle cue"),
            ("Night breath", "33-40", "Elder Oak moonbeam, slow hush rhythm"),
            ("Sleep blessing", "41-50", "Moon goodnight song, gentle bye-bye"),
        ],
        "key_scenes": [
            ("Dusk meadow, crescent moon, Caly Seed glows soft", "Hello, sleepy friend. The moon is out."),
            ("Pip peeks from a cozy burrow nest", "I'm Pip. Snuggle time feels so nice."),
            ("Elder Oak trunk lit by moonbeam", "Elder Oak watches over us at night."),
            ("Caregiver rocks arms gently", "Your grown-up can snuggle you close."),
            ("Stars twinkle one by one", "God made the night gentle and safe."),
            ("Pip closes eyes, slow breath circle", "Shhh. Rest now. You are loved."),
            ("Moon and friends wave goodnight", "Sweet dreams, little one."),
        ],
        "chapters": "~60s, ~150s, ~240s: star peek, snuggle nest, night breath",
        "beats": [
            ("Hello, sleepy friend. The moon is out.", "welcome"),
            ("I'm Pip. Snuggle time feels so nice.", "friend"),
            ("Elder Oak watches over us at night.", "mentor"),
            ("Your grown-up can snuggle you close.", "caregiver"),
            ("God made the night gentle and safe.", "lesson"),
            ("Shhh. Rest now. You are loved.", "rest"),
            ("Sweet dreams, little one.", "farewell"),
        ],
    },
    {
        "id": "pip_twinkle_toes_long",
        "band": "baby",
        "title": "Pip's Twinkle Toes",
        "friend": "Pip",
        "script_num": 14,
        "lesson": "Your body is a gift to move with joy.",
        "christian": "Psalm 139:14 - fearfully and wonderfully made",
        "acts": [
            ("Hello feet", "1-8", "Caly Seed points to toes, Pip wiggles"),
            ("Wiggle dance", "9-20", "Toe twinkle song, caregiver toe-tap mirror"),
            ("Hop and pause", "21-32", "Small hops, giggle, repeat with variation"),
            ("Tired toes", "33-40", "Slow toe wiggle, Elder Oak rest shade"),
            ("Toe blessing", "41-50", "Wonderfully made refrain, bye-bye wiggle"),
        ],
        "key_scenes": [
            ("Sunny patch, Caly Seed sits, Pip hops in", "Hello! Let's wiggle our twinkle toes."),
            ("Close-up Pip feet wiggling", "I'm Pip! Watch my toes go twinkle-twinkle."),
            ("Elder Oak root bench, warm light", "Elder Oak says every part of you is special."),
            ("Caregiver taps toes gently", "Your grown-up can wiggle toes with you."),
            ("Pip hops in a tiny circle", "Hop, hop! God made you to move with joy."),
            ("Slow wiggle, toes rest", "Twinkle... rest. You did so well."),
            ("Pip waves a foot goodbye", "Bye-bye, twinkle toes!"),
        ],
        "chapters": "~60s, ~150s, ~240s: wiggle dance, hop and pause, tired toes rest",
        "beats": [
            ("Hello! Let's wiggle our twinkle toes.", "welcome"),
            ("I'm Pip! Watch my toes go twinkle-twinkle.", "friend"),
            ("Elder Oak says every part of you is special.", "mentor"),
            ("Your grown-up can wiggle toes with you.", "caregiver"),
            ("Hop, hop! God made you to move with joy.", "play"),
            ("Twinkle... rest. You did so well.", "rest"),
            ("Bye-bye, twinkle toes!", "farewell"),
        ],
    },
    {
        "id": "pip_rainbow_wave_long",
        "band": "baby",
        "title": "Pip's Rainbow Wave",
        "friend": "Pip",
        "script_num": 15,
        "lesson": "After rain comes color and hope.",
        "christian": "Genesis 9:13 - rainbow as a sign of promise",
        "acts": [
            ("After rain", "1-8", "Drops stop, Caly Seed hello, Pip shakes fur"),
            ("Color peek", "9-20", "Rainbow arc appears, wave hello to colors"),
            ("Color dance", "21-32", "Red orange yellow play, caregiver color point"),
            ("Rainbow rest", "33-40", "Elder Oak under arc, soft color glow"),
            ("Promise wave", "41-50", "Rainbow bye-bye, promise of good things"),
        ],
        "key_scenes": [
            ("Wet meadow clearing, rainbow forming", "Hello, friend! Look what came after the rain."),
            ("Pip hops toward rainbow colors", "I'm Pip! Red, orange, yellow - hello!"),
            ("Elder Oak framed by rainbow arc", "Elder Oak says rainbows remind us of God's promise."),
            ("Caregiver points to each color", "Your grown-up can name the colors with you."),
            ("Pip waves under green and blue", "Wave hello to every beautiful color!"),
            ("Rainbow fades to soft gold light", "God keeps promises. You are loved."),
            ("Pip and Caly wave under fading arc", "Bye-bye, rainbow. See you again soon."),
        ],
        "chapters": "~60s, ~150s, ~240s: color peek, color dance, rainbow rest",
        "beats": [
            ("Hello, friend! Look what came after the rain.", "welcome"),
            ("I'm Pip! Red, orange, yellow - hello!", "friend"),
            ("Elder Oak says rainbows remind us of God's promise.", "mentor"),
            ("Your grown-up can name the colors with you.", "caregiver"),
            ("Wave hello to every beautiful color!", "play"),
            ("God keeps promises. You are loved.", "lesson"),
            ("Bye-bye, rainbow. See you again soon.", "farewell"),
        ],
    },
    {
        "id": "pip_heartbeat_lullaby_long",
        "band": "baby",
        "title": "Pip's Heartbeat Lullaby",
        "friend": "Pip",
        "script_num": 16,
        "lesson": "You are loved with a steady, never-ending heart.",
        "christian": "Jeremiah 31:3 - loved with everlasting love",
        "acts": [
            ("Quiet hello", "1-8", "Soft pulse light, Caly Seed whisper hello"),
            ("Heartbeat play", "9-20", "Tap chest rhythm, Pip echoes ba-bum sound"),
            ("Caregiver beat", "21-32", "Grown-up heart tap mirror, slow sway"),
            ("Lullaby rise", "33-40", "Elder Oak hum, heartbeat slows to rest"),
            ("Sleep pulse", "41-50", "Fading heartbeat lullaby, goodnight"),
        ],
        "key_scenes": [
            ("Soft pink glow, gentle pulse animation", "Hello, little heart. I'm Caly Seed."),
            ("Pip paw on chest, ears soft", "I'm Pip. Ba-bum, ba-bum. Can you feel it?"),
            ("Elder Oak trunk with warm pulse rings", "Elder Oak's love is steady like a heartbeat."),
            ("Caregiver hand on heart", "Your grown-up's heart beats for you too."),
            ("Pip and Caly sway to slow rhythm", "Ba-bum. You are safe. Ba-bum. You are loved."),
            ("Heartbeat slows, eyes close", "Rest now. God's love never stops beating for you."),
            ("Final soft pulse and wave", "Goodnight, little heart."),
        ],
        "chapters": "~60s, ~150s, ~240s: heartbeat tap, caregiver sway, lullaby rest",
        "beats": [
            ("Hello, little heart. I'm Caly Seed.", "welcome"),
            ("I'm Pip. Ba-bum, ba-bum. Can you feel it?", "friend"),
            ("Elder Oak's love is steady like a heartbeat.", "mentor"),
            ("Your grown-up's heart beats for you too.", "caregiver"),
            ("Ba-bum. You are safe. Ba-bum. You are loved.", "play"),
            ("Rest now. God's love never stops beating for you.", "rest"),
            ("Goodnight, little heart.", "farewell"),
        ],
    },
    # --- TODDLER (Fern) script_num 17-21 ---
    {
        "id": "fern_flower_surprise_long",
        "band": "toddler",
        "title": "Fern's Flower Surprise",
        "friend": "Fern",
        "script_num": 17,
        "lesson": "Small surprises can brighten someone's whole day.",
        "christian": "Proverbs 11:25 - generous soul will be made rich",
        "acts": [
            ("Garden hello", "1-15", "Fern's plot, Caly Sprout welcome, plan a surprise"),
            ("Pick and wrap", "16-35", "Choose flowers, ribbon, practice quiet giggle"),
            ("Surprise walk", "36-55", "Tiptoe path, Elder Oak nod, knock on burrow"),
            ("Joy reveal", "56-75", "Pip opens door, gasp, hug, thank you"),
            ("Share the bloom", "76-100", "Plant extra seeds together, celebrate garden"),
        ],
        "key_scenes": [
            ("Fern's colorful garden gate opens", "Welcome to my garden! I'm Fern the fox."),
            ("Caly Sprout holds a tiny wrapped bouquet", "Let's surprise Pip with flowers today."),
            ("Elder Oak shades the garden path", "Kind surprises are like sunshine for the heart."),
            ("Fern tiptoes with flowers behind back", "Shhh. Quiet steps make the surprise special."),
            ("Pip burrow door opens, eyes wide", "For me? Wow! Thank you, Fern!"),
            ("All friends plant one seed together", "Sharing joy makes friendship grow."),
            ("Garden party wave goodbye", "See you in the garden soon!"),
        ],
        "chapters": "~120s, ~300s, ~480s: pick flowers, surprise walk, plant together",
        "beats": [
            ("Welcome to my garden! I'm Fern the fox.", "welcome"),
            ("Let's surprise Pip with flowers today.", "friend"),
            ("Kind surprises are like sunshine for the heart.", "mentor"),
            ("Shhh. Quiet steps make the surprise special.", "play"),
            ("For me? Wow! Thank you, Fern!", "share"),
            ("Sharing joy makes friendship grow.", "lesson"),
            ("See you in the garden soon!", "farewell"),
        ],
    },
    {
        "id": "fern_patience_pots_long",
        "band": "toddler",
        "title": "Fern's Patience Pots",
        "friend": "Fern",
        "script_num": 18,
        "lesson": "Good things grow when we wait with hope.",
        "christian": "Galatians 6:9 - do not grow weary in doing good",
        "acts": [
            ("Potting day", "1-15", "Empty pots, seeds, Caly Sprout labels"),
            ("Plant and water", "16-35", "Dig, drop seed, water can song"),
            ("Waiting games", "36-55", "Day counter, peek-not-pick rule, Elder Oak story"),
            ("First sprout", "56-75", "Tiny green, cheer, measure with ruler"),
            ("Patience party", "76-100", "All pots checked, celebrate waiting well"),
        ],
        "key_scenes": [
            ("Garden table with clay pots and seed packets", "Today we plant seeds and practice patience."),
            ("Fern drops a seed, Caly covers with soil", "Plant, water, and wait. Good things take time."),
            ("Elder Oak tells a story under the branches", "Elder Oak says hope grows in quiet waiting."),
            ("Calendar pages flip, Fern checks pots daily", "Every day we look, but we don't pull yet."),
            ("Tiny green sprout breaks through soil", "Look! It grew! Waiting was worth it!"),
            ("Fern and Caly do a patience dance", "You waited so well. I'm proud of you."),
            ("Garden sunset, pots in a row", "See you tomorrow, little sprouts!"),
        ],
        "chapters": "~120s, ~300s, ~480s: plant seeds, waiting games, first sprout cheer",
        "beats": [
            ("Today we plant seeds and practice patience.", "welcome"),
            ("Plant, water, and wait. Good things take time.", "friend"),
            ("Elder Oak says hope grows in quiet waiting.", "mentor"),
            ("Every day we look, but we don't pull yet.", "play"),
            ("Look! It grew! Waiting was worth it!", "celebrate"),
            ("You waited so well. I'm proud of you.", "lesson"),
            ("See you tomorrow, little sprouts!", "farewell"),
        ],
    },
    {
        "id": "fern_butterfly_visit_long",
        "band": "toddler",
        "title": "Fern's Butterfly Visit",
        "friend": "Fern",
        "script_num": 19,
        "lesson": "Be gentle with delicate things and people.",
        "christian": "Colossians 3:12 - clothe yourselves with gentleness",
        "acts": [
            ("Garden watch", "1-15", "Butterfly lands, freeze and whisper rules"),
            ("Gentle approach", "16-35", "Slow steps, soft hands, Caly models"),
            ("Butterfly rest", "36-55", "Sits on Fern's nose, giggle quiet, photo"),
            ("Friend shares", "56-75", "Pip wants turn, take turns chart, Elder Oak"),
            ("Fly away wave", "76-100", "Butterfly leaves, gratitude circle"),
        ],
        "key_scenes": [
            ("Sunlit garden, orange butterfly on a daisy", "A butterfly came to visit! Walk softly."),
            ("Fern and Caly Sprout tiptoe closer", "Gentle hands. Gentle steps. Gentle hearts."),
            ("Butterfly rests on Fern's nose", "It trusts you because you were so gentle."),
            ("Elder Oak watches from the garden edge", "God asks us to be gentle with all His creatures."),
            ("Pip waits on a log, Fern invites turn", "Your turn next, Pip. We take turns gently."),
            ("Butterfly flutters up and away", "Thank you for visiting us, little butterfly."),
            ("Friends wave as butterfly crosses meadow", "Gentleness makes friends of us all."),
        ],
        "chapters": "~120s, ~300s, ~480s: gentle approach, butterfly rest, take turns",
        "beats": [
            ("A butterfly came to visit! Walk softly.", "welcome"),
            ("Gentle hands. Gentle steps. Gentle hearts.", "friend"),
            ("God asks us to be gentle with all His creatures.", "mentor"),
            ("Your turn next, Pip. We take turns gently.", "share"),
            ("It trusts you because you were so gentle.", "lesson"),
            ("Thank you for visiting us, little butterfly.", "celebrate"),
            ("Gentleness makes friends of us all.", "farewell"),
        ],
    },
    {
        "id": "fern_weeding_teamwork_long",
        "band": "toddler",
        "title": "Fern's Weeding Teamwork",
        "friend": "Fern",
        "script_num": 20,
        "lesson": "Working together makes hard jobs feel lighter.",
        "christian": "Ecclesiastes 4:9 - two are better than one",
        "acts": [
            ("Weedy problem", "1-15", "Garden overrun, Fern sighs, call for help"),
            ("Team forms", "16-35", "Pip, Moss invite, assign rows, tools song"),
            ("Weed and sing", "36-55", "Pull rhythm, pile weeds, Elder Oak cheer"),
            ("Snack break", "56-75", "Share water and berries, rest in shade"),
            ("Clean garden", "76-100", "Reveal neat rows, plant new flowers, celebrate"),
        ],
        "key_scenes": [
            ("Overgrown garden patch, Fern hands on hips", "Oh no! Too many weeds. I need help."),
            ("Caly Sprout gathers friends with a sign", "Many hands make light work. Let's team up!"),
            ("Elder Oak roots frame the garden rows", "Elder Oak says friends help friends grow."),
            ("Fern, Pip, Moss pull weeds in a rhythm", "Pull, pull, sing! Teamwork makes it fun."),
            ("Shade break with shared berries", "Rest and share. Then we finish strong."),
            ("Garden neat and bright with new flowers", "We did it together! What a beautiful garden."),
            ("Team high-five and garden gate close", "Teamwork today, friendship forever."),
        ],
        "chapters": "~120s, ~300s, ~480s: team forms, weed and sing, clean garden cheer",
        "beats": [
            ("Oh no! Too many weeds. I need help.", "welcome"),
            ("Many hands make light work. Let's team up!", "friend"),
            ("Elder Oak says friends help friends grow.", "mentor"),
            ("Pull, pull, sing! Teamwork makes it fun.", "play"),
            ("Rest and share. Then we finish strong.", "share"),
            ("We did it together! What a beautiful garden.", "celebrate"),
            ("Teamwork today, friendship forever.", "farewell"),
        ],
    },
    {
        "id": "fern_seed_gift_long",
        "band": "toddler",
        "title": "Fern's Seed Gift",
        "friend": "Fern",
        "script_num": 21,
        "lesson": "Giving something you love can grow more love.",
        "christian": "2 Corinthians 9:7 - God loves a cheerful giver",
        "acts": [
            ("Special seeds", "1-15", "Fern's favorite seed packet, hard to share"),
            ("Gift idea", "16-35", "Caly suggests giving, Fern thinks, Elder Oak"),
            ("Wrap and walk", "36-55", "Decorate packet, walk to Moss's house"),
            ("Give and plant", "56-75", "Moss thanks Fern, plant side by side"),
            ("Double bloom", "76-100", "Both gardens have same flower, celebrate"),
        ],
        "key_scenes": [
            ("Fern holds a shiny seed packet close", "These are my favorite seeds. I love them."),
            ("Caly Sprout kneels beside Fern", "What if sharing them grows something even better?"),
            ("Elder Oak drops an acorn near Fern's paw", "A gift given freely comes back in friendship."),
            ("Fern decorates the packet with a ribbon", "For you, Moss. I want you to grow these too."),
            ("Moss hugs Fern at his garden gate", "Thank you! I'll take good care of them."),
            ("Two matching flowers bloom in two gardens", "Now we both have beauty because you shared."),
            ("Fern waves from her gate at sunset", "Sharing seeds planted joy in two places."),
        ],
        "chapters": "~120s, ~300s, ~480s: gift idea, give and plant, double bloom",
        "beats": [
            ("These are my favorite seeds. I love them.", "welcome"),
            ("What if sharing them grows something even better?", "friend"),
            ("A gift given freely comes back in friendship.", "mentor"),
            ("For you, Moss. I want you to grow these too.", "share"),
            ("Thank you! I'll take good care of them.", "include"),
            ("Now we both have beauty because you shared.", "celebrate"),
            ("Sharing seeds planted joy in two places.", "farewell"),
        ],
    },
    # --- CHILD (Moss) script_num 22-26 ---
    {
        "id": "moss_bridge_builders_long",
        "band": "child",
        "title": "Moss the Bridge Builders",
        "friend": "Moss",
        "script_num": 22,
        "lesson": "Building bridges connects hearts across differences.",
        "christian": "Ephesians 2:14 - Christ is our peace who breaks down walls",
        "acts": [
            ("Stream divide", "1-25", "Creek splits meadow, friends on two sides"),
            ("Plan the bridge", "26-55", "Moss blueprint, gather wood, Caly Bud tools"),
            ("Build together", "56-85", "Hammer rhythm, Reed measures, team roles"),
            ("Cross and cheer", "86-115", "First crossing, hand-in-paw, Elder Oak blesses"),
            ("Bridge party", "116-150", "Decorate rails, picnic both sides, song"),
        ],
        "key_scenes": [
            ("Wide creek, friends waving from opposite banks", "We're stuck on different sides. We need a bridge."),
            ("Moss unfurls a hand-drawn bridge plan", "Moss the bear builds bridges, not walls."),
            ("Caly Bud holds nails, Reed holds measuring stick", "Every friend has a job. Together we can do this."),
            ("Elder Oak leans a sturdy branch as anchor", "Strong roots hold up what friends build together."),
            ("Final plank placed, bridge complete", "Step by step, we connected two worlds."),
            ("All friends cross hand in hand", "Crossing together is better than staying apart."),
            ("Bridge decorated with flowers and a banner", "Bridge builders forever! See you on the path."),
        ],
        "chapters": "~180s, ~420s, ~720s: plan bridge, build together, cross and cheer",
        "beats": [
            ("We're stuck on different sides. We need a bridge.", "welcome"),
            ("Moss the bear builds bridges, not walls.", "friend"),
            ("Strong roots hold up what friends build together.", "mentor"),
            ("Every friend has a job. Together we can do this.", "include"),
            ("Step by step, we connected two worlds.", "lesson"),
            ("Crossing together is better than staying apart.", "celebrate"),
            ("Bridge builders forever! See you on the path.", "farewell"),
        ],
    },
    {
        "id": "moss_lost_and_found_long",
        "band": "child",
        "title": "Moss Lost and Found",
        "friend": "Moss",
        "script_num": 23,
        "lesson": "Helping someone find what matters shows real friendship.",
        "christian": "Luke 15:4 - leaves the ninety-nine to find the one",
        "acts": [
            ("Lost ribbon", "1-25", "Pip's favorite ribbon missing, Pip sad"),
            ("Search party", "26-55", "Moss organizes grid search, Caly Bud map"),
            ("Clue trail", "56-85", "Feather, paw print, Reed spots from tree"),
            ("Found in bush", "86-115", "Ribbon tangled, gentle untangle, Pip relief"),
            ("Search celebration", "116-150", "Thank you circle, Moss medal, Elder Oak word"),
        ],
        "key_scenes": [
            ("Pip sniffling, empty paw where ribbon was", "My ribbon is lost. It was my favorite."),
            ("Moss puts on explorer hat, opens notebook", "Don't worry, Pip. We'll find it together."),
            ("Search grid drawn in dirt, friends assigned zones", "Everyone has a search spot. No friend left behind."),
            ("Reed calls from a branch, points to bush", "I see something blue near the berry bush!"),
            ("Moss gently untangles ribbon from thorns", "Found it! You never gave up on your friend."),
            ("Pip hugs Moss, ribbon back on ear", "Thank you for looking until you found it."),
            ("Elder Oak gifts Moss a kindness leaf badge", "Seekers of the lost are heroes in God's eyes."),
        ],
        "chapters": "~180s, ~420s, ~720s: search party, clue trail, found celebration",
        "beats": [
            ("My ribbon is lost. It was my favorite.", "welcome"),
            ("Don't worry, Pip. We'll find it together.", "friend"),
            ("Everyone has a search spot. No friend left behind.", "include"),
            ("I see something blue near the berry bush!", "play"),
            ("Found it! You never gave up on your friend.", "lesson"),
            ("Thank you for looking until you found it.", "celebrate"),
            ("Seekers of the lost are heroes in God's eyes.", "farewell"),
        ],
    },
    {
        "id": "moss_campfire_stories_long",
        "band": "child",
        "title": "Moss's Campfire Stories",
        "friend": "Moss",
        "script_num": 24,
        "lesson": "Stories connect us to wisdom passed down with love.",
        "christian": "Deuteronomy 6:7 - teach diligently to your children",
        "acts": [
            ("Camp setup", "1-25", "Tent, fire ring, Moss gathers firewood"),
            ("First story", "26-55", "Elder Oak tale of brave seed, friends listen"),
            ("Everyone shares", "56-85", "Each friend tells one minute story, Caly Bud"),
            ("Star gazing", "86-115", "Quiet moment, constellation game, hush"),
            ("Story promise", "116-150", "Promise to tell stories again, marshmallow toast"),
        ],
        "key_scenes": [
            ("Forest clearing, campfire crackling, stars above", "Welcome to Moss's campfire circle."),
            ("Moss in camp chair, friends on logs", "Tonight we share stories that warm the heart."),
            ("Elder Oak's face lit by firelight", "Long ago, a tiny seed trusted the soil and grew."),
            ("Fern tells a garden story, Pip claps", "Every friend has a story worth hearing."),
            ("Caly Bud points at star shapes", "Stories are like stars. They light up the dark."),
            ("Moss passes a talking stick for turns", "Listen first. Then your turn to share."),
            ("Friends toast marshmallows, fire dims", "Same time next week? Stories keep us close."),
        ],
        "chapters": "~180s, ~420s, ~720s: Elder Oak story, everyone shares, star gazing hush",
        "beats": [
            ("Welcome to Moss's campfire circle.", "welcome"),
            ("Tonight we share stories that warm the heart.", "friend"),
            ("Long ago, a tiny seed trusted the soil and grew.", "mentor"),
            ("Every friend has a story worth hearing.", "include"),
            ("Listen first. Then your turn to share.", "lesson"),
            ("Stories are like stars. They light up the dark.", "rest"),
            ("Same time next week? Stories keep us close.", "farewell"),
        ],
    },
    {
        "id": "moss_apology_path_long",
        "band": "child",
        "title": "Moss and the Apology Path",
        "friend": "Moss",
        "script_num": 25,
        "lesson": "Saying sorry and forgiving mends what was broken.",
        "christian": "Colossians 3:13 - forgive as the Lord forgave you",
        "acts": [
            ("The break", "1-25", "Moss accidentally breaks Fern's pot, Fern upset"),
            ("Cool down", "26-55", "Separate paths, Caly Bud breathing, Elder Oak"),
            ("Apology walk", "56-85", "Moss walks apology path, practices words"),
            ("I'm sorry", "86-115", "Moss apologizes, Fern listens, repair together"),
            ("New pot", "116-150", "Build new pot, plant together, path complete"),
        ],
        "key_scenes": [
            ("Broken clay pot, Fern with tears, Moss looking down", "I didn't mean to break it. Fern is so sad."),
            ("Caly Bud guides Moss to a quiet bench", "Before we fix the pot, let's calm our hearts."),
            ("Elder Oak points to a winding stone path", "The apology path helps us say what matters."),
            ("Moss walks path rehearsing: I am sorry", "Sorry means I care that I hurt you."),
            ("Moss kneels before Fern with new clay", "I'm sorry I broke your pot. Can we fix it together?"),
            ("Fern nods, both hands shape new pot", "I forgive you. Let's make something new."),
            ("New pot planted, friends walk path again smiling", "Repair makes friendship stronger than before."),
        ],
        "chapters": "~180s, ~420s, ~720s: cool down, apology walk, new pot together",
        "beats": [
            ("I didn't mean to break it. Fern is so sad.", "welcome"),
            ("Before we fix the pot, let's calm our hearts.", "friend"),
            ("The apology path helps us say what matters.", "mentor"),
            ("Sorry means I care that I hurt you.", "lesson"),
            ("I'm sorry I broke your pot. Can we fix it together?", "repair"),
            ("I forgive you. Let's make something new.", "include"),
            ("Repair makes friendship stronger than before.", "celebrate"),
        ],
    },
    {
        "id": "moss_team_harvest_long",
        "band": "child",
        "title": "Moss's Team Harvest",
        "friend": "Moss",
        "script_num": 26,
        "lesson": "Sharing the harvest blesses everyone at the table.",
        "christian": "Acts 2:46 - broke bread with glad and generous hearts",
        "acts": [
            ("Harvest eve", "1-25", "Garden ripe, Moss counts baskets needed"),
            ("Morning pick", "26-55", "Dawn harvest, roles assigned, work song"),
            ("Sort and share", "56-85", "Divide into shares, one for neighbors"),
            ("Community table", "86-115", "Long table setup, invite shy hedgehog"),
            ("Harvest feast", "116-150", "Eat together, thank Elder Oak, dance"),
        ],
        "key_scenes": [
            ("Sunrise over full garden rows, Moss with basket", "Harvest day! The garden gave us so much."),
            ("Friends spread through rows with baskets", "Pick together, share together, feast together."),
            ("Moss divides vegetables into equal piles", "We keep some and share some. That's how we grow."),
            ("Elder Oak shades a long wooden table", "God gives seedtime and harvest. Give thanks."),
            ("Shy hedgehog invited to sit at table", "There's always room for one more friend."),
            ("All friends hold hands before eating", "Thank you for food, friends, and this day."),
            ("Sunset cleanup, baskets empty, hearts full", "Team harvest complete. Until next season!"),
        ],
        "chapters": "~180s, ~420s, ~720s: morning pick, sort and share, community feast",
        "beats": [
            ("Harvest day! The garden gave us so much.", "welcome"),
            ("Pick together, share together, feast together.", "friend"),
            ("God gives seedtime and harvest. Give thanks.", "mentor"),
            ("We keep some and share some. That's how we grow.", "share"),
            ("There's always room for one more friend.", "include"),
            ("Thank you for food, friends, and this day.", "celebrate"),
            ("Team harvest complete. Until next season!", "farewell"),
        ],
    },
    # --- TWEEN (Reed) script_num 27-31 ---
    {
        "id": "reed_rumor_mist_long",
        "band": "tween",
        "title": "Reed and the Rumor Mist",
        "friend": "Reed",
        "script_num": 27,
        "lesson": "Check facts before words spread like fog.",
        "christian": "Proverbs 18:17 - first to plead his case seems right",
        "acts": [
            ("Misty morning", "1-30", "Fog over meadow, whispers start about Moss"),
            ("Whisper chain", "31-70", "Rumor grows, friends avoid Moss, Reed notices"),
            ("Perch and pause", "71-110", "Reed climbs perch, Caly Sprig fact checklist"),
            ("Truth clears", "111-150", "Reed asks Moss directly, rumor dissolves"),
            ("Mist lesson", "151-200", "Group talk about rumors, Elder Oak proverb"),
        ],
        "key_scenes": [
            ("Thick fog, friends whispering behind paws", "Something feels wrong. Stories are spreading."),
            ("Reed on low branch, ears perked", "I'm Reed. Before I speak, I perch and listen."),
            ("Caly Sprig holds a fact-check feather", "Is it true? Is it kind? Is it needed?"),
            ("Reed flies to Moss, asks face to face", "Moss, I heard something. Can we talk honestly?"),
            ("Moss explains, fog literally lifts", "The truth was simpler than the rumor."),
            ("Elder Oak shares proverb about rushing words", "Words spread fast. Truth takes courage."),
            ("Friends apologize to Moss in a circle", "We checked facts. We won't spread mist again."),
        ],
        "chapters": "~240s, ~600s, ~960s: whisper chain, perch and pause, truth clears",
        "beats": [
            ("Something feels wrong. Stories are spreading.", "welcome"),
            ("I'm Reed. Before I speak, I perch and listen.", "friend"),
            ("Is it true? Is it kind? Is it needed?", "lesson"),
            ("Words spread fast. Truth takes courage.", "mentor"),
            ("Moss, I heard something. Can we talk honestly?", "repair"),
            ("The truth was simpler than the rumor.", "celebrate"),
            ("We checked facts. We won't spread mist again.", "farewell"),
        ],
    },
    {
        "id": "reed_patience_listeners_long",
        "band": "tween",
        "title": "Reed's Patience Listeners",
        "friend": "Reed",
        "script_num": 28,
        "lesson": "Listening fully is a gift that helps others feel seen.",
        "christian": "James 1:19 - be quick to listen, slow to speak",
        "acts": [
            ("Busy perch", "1-30", "Reed interrupted often, Fern needs to talk"),
            ("Listener pledge", "31-70", "Caly Sprig challenge, no interrupt timer"),
            ("Fern's story", "71-110", "Fern shares worry, Reed listens whole way"),
            ("More friends", "111-150", "Pip, Moss share, Reed repeats back"),
            ("Listener circle", "151-200", "Practice pairs, Elder Oak blessing, badges"),
        ],
        "key_scenes": [
            ("Reed's wisdom perch, friends lined up to talk", "Everyone wants to talk. Who will listen?"),
            ("Reed closes beak, opens ears wide", "Today I practice patience listening."),
            ("Caly Sprig sets a sand timer on the branch", "Let them finish. Then you respond."),
            ("Fern talks about garden worry, Reed nods", "I hear you. You're afraid the frost will come."),
            ("Elder Oak: roots listen to rain before they drink", "Deep listening helps friends grow strong."),
            ("Reed repeats Moss's words back accurately", "Did I understand you right? Tell me more."),
            ("Circle of friends with listener leaf badges", "Patience listeners change the whole meadow."),
        ],
        "chapters": "~240s, ~600s, ~960s: listener pledge, Fern's story, listener circle",
        "beats": [
            ("Everyone wants to talk. Who will listen?", "welcome"),
            ("Today I practice patience listening.", "friend"),
            ("Let them finish. Then you respond.", "interactive"),
            ("Deep listening helps friends grow strong.", "mentor"),
            ("I hear you. You're afraid the frost will come.", "lesson"),
            ("Did I understand you right? Tell me more.", "include"),
            ("Patience listeners change the whole meadow.", "celebrate"),
        ],
    },
    {
        "id": "reed_honest_feather_long",
        "band": "tween",
        "title": "Reed's Honest Feather",
        "friend": "Reed",
        "script_num": 29,
        "lesson": "Honesty weighs lightly; lies grow heavy over time.",
        "christian": "Proverbs 12:22 - lying lips are an abomination to the Lord",
        "acts": [
            ("Feather find", "1-30", "Reed finds glowing feather, tempted to keep secret"),
            ("Small lie", "31-70", "Says he knows nothing, feather grows heavy"),
            ("Heavy flight", "71-110", "Cannot fly well, Caly Sprig truth talk"),
            ("Confession", "111-150", "Reed tells truth to Sage, feather lightens"),
            ("Honesty pact", "151-200", "Friends make honesty feather pact, Elder Oak"),
        ],
        "key_scenes": [
            ("Reed finds a silver feather in the grass", "I found something special. Should I tell?"),
            ("Reed hides feather, tells friends he saw nothing", "A small lie. No one will know."),
            ("Feather grows heavy, Reed struggles to fly", "Lies get heavier every moment you carry them."),
            ("Caly Sprig sits beside grounded Reed", "Truth may be hard, but it sets you free."),
            ("Reed shows feather, tells Sage the truth", "I found it and hid it. I'm sorry I lied."),
            ("Feather glows light, Reed lifts off easily", "Honesty makes your wings strong again."),
            ("Friends each hold a feather, honesty pledge", "We choose truth, even when it's hard."),
        ],
        "chapters": "~240s, ~600s, ~960s: small lie, heavy flight, confession and pact",
        "beats": [
            ("I found something special. Should I tell?", "welcome"),
            ("A small lie. No one will know.", "friend"),
            ("Lies get heavier every moment you carry them.", "lesson"),
            ("Truth may be hard, but it sets you free.", "mentor"),
            ("I found it and hid it. I'm sorry I lied.", "repair"),
            ("Honesty makes your wings strong again.", "celebrate"),
            ("We choose truth, even when it's hard.", "farewell"),
        ],
    },
    {
        "id": "reed_storm_shelter_long",
        "band": "tween",
        "title": "Reed's Storm Shelter",
        "friend": "Reed",
        "script_num": 30,
        "lesson": "Storms pass faster when friends shelter together.",
        "christian": "Psalm 46:1 - God is our refuge and strength",
        "acts": [
            ("Storm warning", "1-30", "Dark clouds, wind rises, friends scatter scared"),
            ("Shelter call", "31-70", "Reed calls all to Elder Oak hollow"),
            ("Inside together", "71-110", "Share blankets, stories, calm breathing"),
            ("Storm peak", "111-150", "Loudest thunder, group hug, song"),
            ("Clear sky", "151-200", "Storm ends, rainbow, thank you circle"),
        ],
        "key_scenes": [
            ("Dark clouds rolling, wind bending flowers", "A big storm is coming. Everyone find shelter!"),
            ("Reed circles above, calling friends below", "Follow me to Elder Oak. We'll be safe together."),
            ("Inside hollow trunk, friends huddle close", "Close together. Breathe slow. You're not alone."),
            ("Thunder crack, Pip trembles, Moss holds paw", "Storms are loud, but they don't last forever."),
            ("Elder Oak trunk solid against wind", "God is our shelter when the world feels wild."),
            ("Reed leads a quiet hum, hearts steady", "We weathered it because we stayed together."),
            ("Rain stops, rainbow over meadow, friends emerge", "The storm passed. We are stronger together."),
        ],
        "chapters": "~240s, ~600s, ~960s: shelter call, inside together, clear sky",
        "beats": [
            ("A big storm is coming. Everyone find shelter!", "welcome"),
            ("Follow me to Elder Oak. We'll be safe together.", "friend"),
            ("God is our shelter when the world feels wild.", "mentor"),
            ("Close together. Breathe slow. You're not alone.", "rest"),
            ("Storms are loud, but they don't last forever.", "lesson"),
            ("We weathered it because we stayed together.", "celebrate"),
            ("The storm passed. We are stronger together.", "farewell"),
        ],
    },
    {
        "id": "reed_mentor_circle_long",
        "band": "tween",
        "title": "Reed's Mentor Circle",
        "friend": "Reed",
        "script_num": 31,
        "lesson": "Learning from elders and teaching younger ones completes the circle.",
        "christian": "Titus 2:3-4 - older teaching what is good",
        "acts": [
            ("Circle forms", "1-30", "Reed invites multi-age circle under Elder Oak"),
            ("Elder lesson", "31-70", "Elder Oak shares tree ring wisdom"),
            ("Reed teaches", "71-110", "Reed teaches Pip listening game"),
            ("Pip teaches", "111-150", "Pip teaches joy clap, everyone learns"),
            ("Circle close", "151-200", "Each friend states one lesson learned"),
        ],
        "key_scenes": [
            ("Friends of all ages sit in circle under oak", "Welcome to the mentor circle. Everyone teaches."),
            ("Elder Oak shows tree rings in a cut slice", "Each ring is a year of wisdom. I share mine."),
            ("Reed demonstrates listening perch to Pip", "I learned from Elder Oak. Now I teach you."),
            ("Pip claps a joy rhythm, Moss tries it", "Even the smallest friend has wisdom to share."),
            ("Caly Sprig writes lessons on leaf scrolls", "Teaching and learning go round and round."),
            ("Each friend holds hand of younger and older", "The circle never breaks when we pass it on."),
            ("Circle stands, bows to Elder Oak together", "Mentor circle complete. Wisdom grows here."),
        ],
        "chapters": "~240s, ~600s, ~960s: Elder lesson, Reed teaches, circle close",
        "beats": [
            ("Welcome to the mentor circle. Everyone teaches.", "welcome"),
            ("I learned from Elder Oak. Now I teach you.", "friend"),
            ("Each ring is a year of wisdom. I share mine.", "mentor"),
            ("Even the smallest friend has wisdom to share.", "include"),
            ("Teaching and learning go round and round.", "lesson"),
            ("The circle never breaks when we pass it on.", "celebrate"),
            ("Mentor circle complete. Wisdom grows here.", "farewell"),
        ],
    },
    # --- TEEN (Sage) script_num 32-36 ---
    {
        "id": "sage_truth_telling_long",
        "band": "teen",
        "title": "Sage and Truth Telling",
        "friend": "Sage",
        "script_num": 32,
        "lesson": "Speaking truth with courage protects everyone you love.",
        "christian": "Ephesians 4:15 - speaking truth in love",
        "acts": [
            ("Hidden problem", "1-45", "Trail damage covered up, Sage discovers truth"),
            ("Pressure to hide", "46-90", "Friends say stay quiet, Sage conflicted"),
            ("Caly counsel", "91-135", "Caly Vine truth-in-love framework"),
            ("Tell elders", "136-180", "Sage tells Elder Oak and Reed, plan repair"),
            ("Trail fix", "181-225", "Community repairs trail, honesty celebrated"),
            ("Truth covenant", "226-300", "Friends sign truth covenant, Sage speech"),
        ],
        "key_scenes": [
            ("Damaged trail sign hidden under branches", "Someone hid this damage. People could get hurt."),
            ("Friends whisper: just leave it, not our problem", "Staying quiet feels easier. But is it right?"),
            ("Caly Vine with communication board open", "Truth without love can wound. Love without truth can harm."),
            ("Sage stands before Elder Oak, speaks clearly", "The trail bridge is broken. We need to fix it now."),
            ("Community works together repairing bridge", "Truth brought us together to make things right."),
            ("Elder Oak places paw on Sage's shoulder", "Courageous truth protects the whole community."),
            ("Friends sign a leaf-scroll truth covenant", "We choose to tell the truth, even when it's hard."),
        ],
        "chapters": "~360s, ~900s, ~1440s: pressure to hide, tell elders, trail fix",
        "beats": [
            ("Someone hid this damage. People could get hurt.", "welcome"),
            ("Staying quiet feels easier. But is it right?", "friend"),
            ("Truth without love can wound. Love without truth can harm.", "lesson"),
            ("The trail bridge is broken. We need to fix it now.", "repair"),
            ("Courageous truth protects the whole community.", "mentor"),
            ("Truth brought us together to make things right.", "celebrate"),
            ("We choose to tell the truth, even when it's hard.", "farewell"),
        ],
    },
    {
        "id": "sage_peer_pressure_long",
        "band": "teen",
        "title": "Sage and Peer Pressure",
        "friend": "Sage",
        "script_num": 33,
        "lesson": "You can say no and still belong.",
        "christian": "Romans 12:2 - do not conform to the pattern of this world",
        "acts": [
            ("Group invite", "1-45", "Popular group dares Sage to cross unsafe log"),
            ("Inner conflict", "46-90", "Want to fit in vs know it's wrong"),
            ("Anchor talk", "91-135", "Laurel shares her teen no story, Caly Vine"),
            ("Clear no", "136-180", "Sage says no with respect, offers alternative"),
            ("Real friends", "181-225", "True friends join Sage on safe path"),
            ("Pressure debrief", "226-300", "Group discusses pressure, Elder Oak closes"),
        ],
        "key_scenes": [
            ("Teen friends at a creek with a slippery log", "Cross it to prove you're brave. Everyone's doing it."),
            ("Sage steps back, antlers lowered in thought", "I want friends. But this doesn't feel right."),
            ("Laurel perches nearby, shares her story", "I said no once and found better friends after."),
            ("Caly Vine: your values are your anchor", "An anchor holds you steady when waves push hard."),
            ("Sage speaks firmly but kindly: I'll pass", "No thank you. Let's find a safer way across."),
            ("Reed and Moss join Sage on the stone bridge", "Real friends respect your no."),
            ("Elder Oak: integrity is choosing the harder right", "You stayed true. That is real courage."),
        ],
        "chapters": "~360s, ~900s, ~1440s: inner conflict, clear no, real friends",
        "beats": [
            ("Cross it to prove you're brave. Everyone's doing it.", "welcome"),
            ("I want friends. But this doesn't feel right.", "friend"),
            ("An anchor holds you steady when waves push hard.", "lesson"),
            ("No thank you. Let's find a safer way across.", "interactive"),
            ("Real friends respect your no.", "include"),
            ("You stayed true. That is real courage.", "mentor"),
            ("Integrity is choosing the harder right.", "celebrate"),
        ],
    },
    {
        "id": "sage_forgiveness_trail_long",
        "band": "teen",
        "title": "Sage's Forgiveness Trail",
        "friend": "Sage",
        "script_num": 34,
        "lesson": "Forgiveness frees you from carrying old hurt.",
        "christian": "Matthew 6:14 - if you forgive others, your Father will forgive you",
        "acts": [
            ("Old wound", "1-45", "Sage remembers Reed's harsh words months ago"),
            ("Heavy pack", "46-90", "Metaphor: Sage carries heavy stone in pack"),
            ("Trail start", "91-135", "Elder Oak sends Sage on forgiveness trail"),
            ("Stones down", "136-180", "At each marker, Sage sets down a stone"),
            ("Reed meeting", "181-225", "Reed apologizes sincerely, Sage forgives"),
            ("Light pack", "226-300", "Sage finishes trail unburdened, helps others"),
        ],
        "key_scenes": [
            ("Sage on trail with visibly heavy backpack", "I've carried this hurt for too long."),
            ("Each trail marker is a stone cairn", "Forgiveness is a path, not a single step."),
            ("Elder Oak at trailhead, gentle voice", "Put down what weighs you down. Travel lighter."),
            ("Sage places stone at marker one: the anger", "I release this. It doesn't serve me anymore."),
            ("Reed waits at trail midpoint, head bowed", "I was wrong. I'm sorry. Will you forgive me?"),
            ("Sage and Reed walk final segment together", "Forgiveness doesn't forget. It frees."),
            ("Sage's pack glows light at trail end", "I am free. I can help others on this path too."),
        ],
        "chapters": "~360s, ~900s, ~1440s: heavy pack, stones down, Reed meeting",
        "beats": [
            ("I've carried this hurt for too long.", "welcome"),
            ("Forgiveness is a path, not a single step.", "lesson"),
            ("Put down what weighs you down. Travel lighter.", "mentor"),
            ("I release this. It doesn't serve me anymore.", "rest"),
            ("I was wrong. I'm sorry. Will you forgive me?", "repair"),
            ("Forgiveness doesn't forget. It frees.", "friend"),
            ("I am free. I can help others on this path too.", "celebrate"),
        ],
    },
    {
        "id": "sage_service_saturday_long",
        "band": "teen",
        "title": "Sage's Service Saturday",
        "friend": "Sage",
        "script_num": 35,
        "lesson": "Serving others turns faith into visible love.",
        "christian": "Galatians 5:13 - serve one another in love",
        "acts": [
            ("Saturday plan", "1-45", "Sage wanted free day, Laurel invites serve"),
            ("Food pantry", "46-90", "Sort donations, meet neighbors, Caly Vine AAC"),
            ("Garden help", "91-135", "Help elder tortoise with weeding, listen"),
            ("Youth clean-up", "136-180", "Trail litter pick, team competition kind"),
            ("Reflection", "181-225", "Circle share: what surprised you today"),
            ("Service habit", "226-300", "Plan monthly service, Sage leads sign-up"),
        ],
        "key_scenes": [
            ("Sage stretching on Saturday morning, relaxed", "I planned to do nothing today."),
            ("Laurel arrives with service Saturday flyer", "What if doing something for others fills you up?"),
            ("Pantry shelves, Sage sorting cans with care", "Every can is someone's meal. That matters."),
            ("Elder tortoise garden, Sage weeds patiently", "Serving can be quiet. Listening is service too."),
            ("Trail clean-up crew with Sage leading", "Our meadow looks better because we showed up."),
            ("Circle under Elder Oak, friends share stories", "I thought I'd lose my day. I gained perspective."),
            ("Sage pins service Saturday sign to board", "Same time next month. Who's in?"),
        ],
        "chapters": "~360s, ~900s, ~1440s: food pantry, garden help, reflection circle",
        "beats": [
            ("I planned to do nothing today.", "welcome"),
            ("What if doing something for others fills you up?", "friend"),
            ("Every can is someone's meal. That matters.", "lesson"),
            ("Serving can be quiet. Listening is service too.", "mentor"),
            ("Our meadow looks better because we showed up.", "share"),
            ("I thought I'd lose my day. I gained perspective.", "celebrate"),
            ("Same time next month. Who's in?", "farewell"),
        ],
    },
    {
        "id": "sage_steady_anchor_long",
        "band": "teen",
        "title": "Sage's Steady Anchor",
        "friend": "Sage",
        "script_num": 36,
        "lesson": "When life shifts, your values keep you steady.",
        "christian": "Hebrews 6:19 - hope as an anchor for the soul",
        "acts": [
            ("Life shifts", "1-45", "Sage faces change: new school, friends moving"),
            ("Drifting feeling", "46-90", "Sage feels unmoored, Caly Vine check-in"),
            ("Anchor craft", "91-135", "Build anchor charm with values engraved"),
            ("Storm test", "136-180", "Metaphor storm, Sage holds anchor, stays firm"),
            ("Values share", "181-225", "Sage shares anchor with younger friends"),
            ("Steady sendoff", "226-300", "Change accepted, anchor worn, hope forward"),
        ],
        "key_scenes": [
            ("Sage looking at moving boxes, friends waving goodbye", "Everything is changing. I feel lost."),
            ("Caly Vine sits with Sage on the ridge", "Change is a wave. Values are your anchor."),
            ("Workshop table, Sage engraves anchor: truth, kindness", "I choose what stays steady inside me."),
            ("Metaphor storm animation, Sage holds anchor chain", "Waves crash. My anchor holds."),
            ("Elder Oak: roots deep, branches flexible", "Bend with change. Stay rooted in what matters."),
            ("Sage gives mini anchor to Moss", "When things shift, remember what you value."),
            ("Sage on new path, anchor visible, chin up", "Steady inside. Ready for what's next."),
        ],
        "chapters": "~360s, ~900s, ~1440s: drifting feeling, anchor craft, values share",
        "beats": [
            ("Everything is changing. I feel lost.", "welcome"),
            ("Change is a wave. Values are your anchor.", "lesson"),
            ("I choose what stays steady inside me.", "friend"),
            ("Bend with change. Stay rooted in what matters.", "mentor"),
            ("Waves crash. My anchor holds.", "rest"),
            ("When things shift, remember what you value.", "share"),
            ("Steady inside. Ready for what's next.", "celebrate"),
        ],
    },
    # --- ADULT (Laurel) script_num 37-41 ---
    {
        "id": "laurel_evening_rest_long",
        "band": "adult",
        "title": "Laurel's Evening Rest",
        "friend": "Laurel",
        "script_num": 37,
        "lesson": "Rest is sacred work that restores body and soul.",
        "christian": "Mark 6:31 - come away and rest awhile",
        "acts": [
            ("Full day", "1-60", "Laurel's busy schedule, Caly Bloom evening check"),
            ("Permission to rest", "61-120", "Elder Oak: even makers need stillness"),
            ("Sunset ritual", "121-210", "Tea, journal, no screens, breath work"),
            ("Body scan", "211-300", "Gentle stretch, gratitude for body"),
            ("Sleep prep", "301-390", "Dim lights, prayer of release, soft song"),
            ("Morning preview", "391-450", "Rest complete, dawn hope, close"),
        ],
        "key_scenes": [
            ("Laurel at desk, calendar full, shoulders tense", "Another full day. When do I rest?"),
            ("Caly Bloom dims lamp, sits nearby quietly", "Rest isn't lazy. It's how we refill."),
            ("Elder Oak at dusk, last light on leaves", "Even the earth rests each night. So may you."),
            ("Laurel pours herbal tea, opens blank journal", "I release today. Tomorrow can wait."),
            ("Gentle stretch sequence on a soft mat", "Thank you, body, for carrying me today."),
            ("Laurel at window, stars appearing, soft hymn", "Into Your hands I rest my day."),
            ("Laurel asleep peacefully, dawn light hints", "Rest well. Morning grace will come."),
        ],
        "chapters": "~540s, ~1350s, ~2160s: sunset ritual, body scan, sleep prep",
        "beats": [
            ("Another full day. When do I rest?", "welcome"),
            ("Rest isn't lazy. It's how we refill.", "friend"),
            ("Even the earth rests each night. So may you.", "mentor"),
            ("I release today. Tomorrow can wait.", "rest"),
            ("Thank you, body, for carrying me today.", "lesson"),
            ("Into Your hands I rest my day.", "celebrate"),
            ("Rest well. Morning grace will come.", "farewell"),
        ],
    },
    {
        "id": "laurel_caregiver_breath_long",
        "band": "adult",
        "title": "Laurel's Caregiver Breath",
        "friend": "Laurel",
        "script_num": 38,
        "lesson": "Caregivers need breath breaks to sustain compassionate care.",
        "christian": "Isaiah 40:31 - renew their strength who wait upon the Lord",
        "acts": [
            ("Care day", "1-60", "Laurel caring for Pip and Fern, no breaks"),
            ("Overwhelm", "61-120", "Tension rises, Caly Bloom notices, pause cue"),
            ("Breath lesson", "121-210", "Elder Oak box breathing, four count"),
            ("Micro breaks", "211-300", "Schedule tiny rests, guilt release"),
            ("Renewed care", "301-390", "Return refreshed, better presence with kids"),
            ("Caregiver pact", "391-450", "Share breath practice with other caregivers"),
        ],
        "key_scenes": [
            ("Laurel juggling snacks, stories, and first aid kit", "Caregiving is love in action. And it's exhausting."),
            ("Caly Bloom gently stops Laurel's busy hands", "You can't pour from an empty cup."),
            ("Elder Oak demonstrates slow breath with rising chest", "Four in, hold, four out. Strength returns."),
            ("Laurel on bench for five minutes, eyes closed", "This minute of breath is a gift to them too."),
            ("Laurel returns to Pip with calm smile", "I'm back. And I'm fully here now."),
            ("Pip and Fern hug Laurel, sensing the calm", "Your peace helps us feel safe."),
            ("Laurel shares breath card with neighbor caregiver", "Caregivers breathe together. We sustain each other."),
        ],
        "chapters": "~540s, ~1350s, ~2160s: breath lesson, micro breaks, renewed care",
        "beats": [
            ("Caregiving is love in action. And it's exhausting.", "welcome"),
            ("You can't pour from an empty cup.", "lesson"),
            ("Four in, hold, four out. Strength returns.", "mentor"),
            ("This minute of breath is a gift to them too.", "rest"),
            ("I'm back. And I'm fully here now.", "caregiver"),
            ("Your peace helps us feel safe.", "celebrate"),
            ("Caregivers breathe together. We sustain each other.", "farewell"),
        ],
    },
    {
        "id": "laurel_gratitude_journal_long",
        "band": "adult",
        "title": "Laurel's Gratitude Journal",
        "friend": "Laurel",
        "script_num": 39,
        "lesson": "Naming blessings daily reshapes how you see hard seasons.",
        "christian": "Psalm 103:2 - forget not all His benefits",
        "acts": [
            ("Hard week", "1-60", "Laurel faces setbacks, mood low, Caly Bloom"),
            ("Journal gift", "61-120", "Elder Oak gives blank journal, three-line rule"),
            ("Day one to three", "121-210", "Small mercies listed, resistance fades"),
            ("Hard day entry", "211-300", "Gratitude alongside grief, honest page"),
            ("Month review", "301-390", "Read back entries, pattern of grace visible"),
            ("Share practice", "391-450", "Laurel teaches journal at community table"),
        ],
        "key_scenes": [
            ("Laurel at kitchen table, rain on window, sighing", "This week felt like one long gray cloud."),
            ("Elder Oak places a simple bound journal on table", "Three lines each night. Blessings you almost missed."),
            ("Laurel writes: warm tea, Pip's giggle, hot shower", "Small things. But my chest feels lighter."),
            ("Hard news day, Laurel writes through tears", "Gratitude doesn't erase pain. It sits beside it."),
            ("Laurel reads a month of entries aloud to Caly", "Look how many mercies hid in ordinary days."),
            ("Community table, Laurel passes journals to friends", "Try three lines tonight. See what changes."),
            ("Laurel closes journal with a smile at the stars", "I won't forget. Thank You for today."),
        ],
        "chapters": "~540s, ~1350s, ~2160s: journal gift, hard day entry, month review",
        "beats": [
            ("This week felt like one long gray cloud.", "welcome"),
            ("Three lines each night. Blessings you almost missed.", "mentor"),
            ("Small things. But my chest feels lighter.", "friend"),
            ("Gratitude doesn't erase pain. It sits beside it.", "lesson"),
            ("Look how many mercies hid in ordinary days.", "celebrate"),
            ("Try three lines tonight. See what changes.", "share"),
            ("I won't forget. Thank You for today.", "farewell"),
        ],
    },
    {
        "id": "laurel_community_table_long",
        "band": "adult",
        "title": "Laurel's Community Table",
        "friend": "Laurel",
        "script_num": 40,
        "lesson": "A shared table turns strangers into family.",
        "christian": "Acts 2:46 - broke bread in their homes with glad hearts",
        "acts": [
            ("Empty chairs", "1-60", "Laurel sets long table, hopes for guests"),
            ("Invitations", "61-120", "Personal invites to lonely neighbors, Caly Bloom"),
            ("Prep together", "121-210", "Guests arrive early to cook, stories flow"),
            ("Meal shared", "211-300", "Pass dishes, inclusive prayer, all voices"),
            ("Hard stories", "301-390", "Safe space for grief and hope at table"),
            ("Table legacy", "391-450", "Monthly plan, everyone signs up to host next"),
        ],
        "key_scenes": [
            ("Long wooden table with mismatched chairs in meadow", "There's room for everyone at this table."),
            ("Laurel hand-delivers invites to quiet neighbors", "You belong here. Will you come eat with us?"),
            ("Kitchen bustle, Moss chopping, Fern arranging flowers", "Many hands make the meal. Many hearts fill the room."),
            ("Elder Oak blessing over bread and soup", "We thank God for food and for each other."),
            ("Guest shares a hard story, table listens fully", "This table holds joy and sorrow both."),
            ("Empty plates, full hearts, laughter at the end", "I hadn't laughed like that in months."),
            ("Laurel pins monthly community table calendar", "Same table, new stories. See you next month."),
        ],
        "chapters": "~540s, ~1350s, ~2160s: invitations, meal shared, table legacy",
        "beats": [
            ("There's room for everyone at this table.", "welcome"),
            ("You belong here. Will you come eat with us?", "friend"),
            ("Many hands make the meal. Many hearts fill the room.", "include"),
            ("We thank God for food and for each other.", "mentor"),
            ("This table holds joy and sorrow both.", "lesson"),
            ("I hadn't laughed like that in months.", "celebrate"),
            ("Same table, new stories. See you next month.", "farewell"),
        ],
    },
    {
        "id": "laurel_legacy_roots_long",
        "band": "adult",
        "title": "Laurel's Legacy Roots",
        "friend": "Laurel",
        "script_num": 41,
        "lesson": "What you plant in others outlives any single season.",
        "christian": "Proverbs 13:22 - good person leaves inheritance for children's children",
        "acts": [
            ("Elder visit", "1-60", "Laurel visits Elder Oak, life review talk"),
            ("Seed memories", "61-120", "Flashback montage of Laurel teaching each friend"),
            ("Plant ceremony", "121-210", "Laurel and friends plant legacy tree together"),
            ("Letters forward", "211-300", "Write letters to future meadow friends"),
            ("Elder Oak ring", "301-390", "Count rings, each ring a lesson passed on"),
            ("Legacy song", "391-450", "Laurel leads song, all generations join"),
        ],
        "key_scenes": [
            ("Laurel and Elder Oak on bench, autumn light", "What will remain when my season changes?"),
            ("Montage: Laurel teaching Pip, Sage, Moss over years", "Every lesson you taught is still growing."),
            ("Hole dug, young tree ready, all friends gathered", "We plant today what shade others will enjoy tomorrow."),
            ("Laurel seals letters in a wooden time capsule", "For the friends who come after us. Read when ready."),
            ("Elder Oak cross-section: dozens of rings visible", "Each ring held a winter and a spring. So will yours."),
            ("Sage reads letter, tears up, hugs Laurel", "Your roots are in everything I am becoming."),
            ("All friends join Laurel's song under the new tree", "Legacy isn't fame. It's love that keeps on rooting."),
        ],
        "chapters": "~540s, ~1350s, ~2160s: seed memories, plant ceremony, legacy song",
        "beats": [
            ("What will remain when my season changes?", "welcome"),
            ("Every lesson you taught is still growing.", "friend"),
            ("Each ring held a winter and a spring. So will yours.", "mentor"),
            ("We plant today what shade others will enjoy tomorrow.", "lesson"),
            ("Your roots are in everything I am becoming.", "share"),
            ("For the friends who come after us. Read when ready.", "celebrate"),
            ("Legacy isn't fame. It's love that keeps on rooting.", "farewell"),
        ],
    },
]

from pathlib import Path
import json

out = Path(__file__).resolve().parents[1] / "videos" / "caly_friends_new_episodes.json"
out.write_text(json.dumps(EPISODES, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(EPISODES)} episodes to {out}")
