# -*- coding: utf-8 -*-
"""Generate expanded Caly content via production API (v2 batch)."""
from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path

API = "https://calyndra-central.azurewebsites.net/api/caly/invoke"
OUT = Path(__file__).resolve().parents[1] / "generated"

PROMPTS = [
    ("faq-expansion-11-20.md", "caregiver", "Write 10 additional FAQ Q&A entries for caregivers using Calyndra AAC. Practical, assent-respecting, no medical or FDA claims."),
    ("lesson-module-11-emotions.md", "child", "Lesson module 11: Naming feelings with AAC symbols. 500 words, age 5-12, sensory-safe tips."),
    ("lesson-module-12-transitions.md", "toddler", "Lesson module 12: Transition words (wait, go, stop, all done) for toddlers. Caregiver modeling guide, 500 words."),
    ("lesson-module-13-peer-pressure.md", "teen", "Lesson module 13: Using AAC to say no to peer pressure. Autonomy-focused, 500 words."),
    ("lesson-module-14-workplace.md", "adult", "Lesson module 14: AAC at work meetings and email. Professional strategies, 500 words."),
    ("lesson-module-15-caregiver-burnout.md", "caregiver", "Lesson module 15: Caregiver sustainability and celebrating small wins with AAC. 500 words, warm tone."),
    ("why-aac-toddler.md", "toddler", "One-page why AAC matters for toddlers 2-4. Warm, concrete, for caregivers. No medical claims."),
    ("why-aac-child.md", "child", "One-page why AAC matters for school-age children. Adventure/story tone. No medical claims."),
    ("why-aac-teen.md", "teen", "One-page why AAC matters for teens. Autonomy and respect. No medical claims."),
    ("why-aac-adult.md", "adult", "One-page why AAC matters for adults. Professional, practical. No medical claims."),
    ("game-hints-tap-the-word.md", "toddler", "Write 15 short encouraging lines Caly Sprout says during Tap the Word game wins and gentle retry hints."),
    ("game-hints-category-quest.md", "child", "Write 15 short encouraging lines Caly Quest says during Category Quest wins and skips."),
    ("game-hints-picture-match.md", "child", "Write 15 short encouraging lines for Picture Match game. Playful, no pressure."),
    ("store-feature-bullets.md", "caregiver", "Write honest App Store feature bullets for Calyndra: symbols, games, Caly chat, age bands. No FDA or medical device claims."),
    ("learn-quick-start.md", "caregiver", "Three things families can do today with Calyndra: try one symbol, play one game, ask Caly one question. 300 words."),
]


def invoke(message: str, audience: str) -> str:
    body = json.dumps({"message": message, "audience": audience}).encode("utf-8")
    req = urllib.request.Request(API, data=body, headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = json.loads(resp.read().decode())
    if not data.get("ok"):
        raise RuntimeError(data.get("error", "invoke failed"))
    return data["response"]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    ok = fail = 0
    for filename, audience, prompt in PROMPTS:
        path = OUT / filename
        print(f"Generating {filename}...")
        try:
            text = invoke(prompt, audience)
            title = filename.replace(".md", "").replace("-", " ").title()
            path.write_text(
                f"# {title}\n\n*Generated by Caly ({audience}) - not medical advice.*\n\n{text}\n",
                encoding="utf-8",
            )
            print(f"  saved {path}")
            ok += 1
        except Exception as exc:
            print(f"  FAILED: {exc}")
            fail += 1
        time.sleep(1.2)
    print(f"Done: {ok} saved, {fail} failed.")


if __name__ == "__main__":
    main()
