# -*- coding: utf-8 -*-
"""Generate Caly lesson content via production API."""
from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path

API = "https://calyndra-central.azurewebsites.net/api/caly/invoke"
OUT = Path(__file__).resolve().parents[1] / "generated"

PROMPTS = [
    ("faq-expansion.md", "caregiver", "Write a comprehensive FAQ (15 Q&A) for caregivers new to AAC with Calyndra. Practical, assent-respecting, no medical claims."),
    ("value-proposition.md", "caregiver", "Write What Calyndra does for your family - 400 words, warm, concrete benefits for AAC learners and caregivers. No FDA claims."),
    ("lesson-module-06-routines.md", "caregiver", "Lesson module: Building morning and bedtime AAC routines. Step-by-step, 500 words, sensory-safe tips."),
    ("lesson-module-07-school.md", "child", "Lesson module for school-age AAC users: advocating for symbol use in class. Encouraging, assent-respecting, 500 words."),
    ("lesson-module-08-teen-autonomy.md", "teen", "Lesson module: Teen self-advocacy with AAC. Autonomy, privacy, when to involve adults. 500 words."),
    ("lesson-module-09-adult-workplace.md", "adult", "Lesson module: AAC in workplace and community. Professional tone, practical strategies, 500 words."),
    ("lesson-module-10-sensory.md", "caregiver", "Lesson module: Sensory-safe symbol grids and reducing overwhelm. 500 words with bullet tips."),
    ("onboarding-caregiver-rich.md", "caregiver", "Three-screen onboarding copy for caregivers: welcome, how AAC helps, assent and consent. Short paragraphs per screen."),
    ("onboarding-toddler-rich.md", "toddler", "Onboarding copy for toddler mode caregivers: how to use Caly Sprout, model one word at a time, celebrate attempts."),
    ("game-feedback-scripts.md", "child", "Write 20 short encouraging feedback lines Caly Quest says after correct AAC game answers. Playful, not pressure."),
    ("picture-symbol-guide.md", "caregiver", "Guide: why picture symbols help early talkers. Evidence-informed but not medical claims. 400 words."),
]


def invoke(message: str, audience: str) -> str:
    body = json.dumps({"message": message, "audience": audience}).encode("utf-8")
    req = urllib.request.Request(API, data=body, headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=90) as resp:
        data = json.loads(resp.read().decode())
    if not data.get("ok"):
        raise RuntimeError(data.get("error", "invoke failed"))
    return data["response"]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for filename, audience, prompt in PROMPTS:
        path = OUT / filename
        print(f"Generating {filename}...")
        try:
            text = invoke(prompt, audience)
            path.write_text(f"# {filename.replace('.md', '').replace('-', ' ').title()}\n\n*Generated by Caly ({audience}) - not medical advice.*\n\n{text}\n", encoding="utf-8")
            print(f"  saved {path}")
        except Exception as exc:
            print(f"  FAILED: {exc}")
        time.sleep(1.5)
    print("Done.")


if __name__ == "__main__":
    main()
