#!/usr/bin/env python3
"""Print GenerateImage-ready prompts for a batch of symbol words across all bands."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROMPT_SCRIPT = ROOT / "scripts" / "symbol_prompt.py"
BANDS = ("sprout", "bud", "sprig", "vine", "bloom", "canopy")

ACTIONS = {
    "sad": "Gentle sad expression with one small tear, caregiver-validated warmth, still kid-safe.",
    "all-done": "Happy Caly pushing blocks away with finished smile, all done gesture.",
    "go": "Happy Caly walking forward with green go arrow.",
    "wait": "Happy patient smile with hourglass or pause palm, five fingers visible.",
    "home": "Happy Caly pointing at cozy house with heart window.",
    "hug": "Happy Caly with open arms for consent hug, small hearts nearby.",
    "sleep": "Happy Caly yawning beside cozy bed with moon and stars.",
    "up": "Happy Caly with arms reaching up and arrow pointing up.",
    "down": "Happy Caly sitting with arrow pointing down.",
    "water": "Happy Caly holding shiny water glass and water drop.",
    "hurt": "Soft concerned but hopeful expression, bandage on knee, kind and kid-safe not scary.",
    "milk": "Happy Caly holding cute milk carton with straw.",
    "juice": "Happy Caly holding bright juice box with straw.",
    "apple": "Happy Caly holding shiny red apple with leaf.",
    "please": "Happy Caly with hands together in please gesture, five fingers visible.",
    "love": "Happy Caly hugging big pink heart with warm smile.",
    "dog": "Happy Caly beside friendly golden puppy wagging tail.",
    "cat": "Happy Caly beside friendly orange kitten purring.",
    "again": "Happy Caly with circular repeat arrows, try again gesture.",
    "ball": "Happy Caly holding red playground ball.",
    "big": "Happy Caly pointing at large star next to small star.",
    "blanket": "Happy Caly wrapped in soft cozy blanket.",
    "book": "Happy Caly holding colorful open picture book.",
    "bus": "Happy Caly beside yellow school bus smiling.",
    "car": "Happy Caly beside small red toy car.",
    "clean": "Happy Caly with sparkle shine on clean surface.",
    "close": "Happy Caly closing door snug with smile.",
    "cold": "Happy Caly with snowflake and ice cube, brr gesture.",
    "cookie": "Happy Caly holding chocolate chip cookie.",
    "daddy": "Happy Caly waving beside warm father figure.",
    "dirty": "Happy Caly with small mud spot, still friendly.",
    "dry": "Happy Caly with fluffy towel drying hands.",
    "friend": "Happy Caly holding hands with friend figure.",
    "hot": "Happy Caly with steaming bowl, hot gesture.",
    "hungry": "Happy Caly rubbing tummy hungry gesture.",
    "listen": "Happy Caly with hand cupped to ear, sound waves.",
    "little": "Happy Caly pointing at tiny star next to big star.",
    "look": "Happy Caly with big friendly eyes looking.",
    "mad": "Frustrated but safe kid expression, not scary.",
    "mommy": "Happy Caly waving beside warm mother figure.",
    "need": "Happy Caly with gentle exclamation, I need gesture.",
    "open": "Happy Caly opening door with light coming through.",
    "scared": "Worried but safe expression, not horror.",
    "shoe": "Happy Caly holding colorful kids sneaker.",
    "tired": "Sleepy yawn expression, gentle and safe.",
    "toy": "Happy Caly hugging teddy bear toy.",
    "want": "Happy Caly reaching toward desired item.",
    "wash": "Happy Caly with soap bubbles washing hands, five fingers.",
    "wet": "Happy Caly with water splash on hands.",
    "symbol_eat": "Happy Caly eating with spoon, large clear eat pictogram.",
    "symbol_happy": "Happy Caly with big joyful smile and sparkles.",
    "symbol_help": "Happy Caly reaching open hand asking for help, five fingers.",
    "symbol_more": "Happy Caly with open palms asking for more.",
    "symbol_play": "Happy Caly jumping with red ball for play.",
    "crib": "Happy Caly beside cozy wooden crib with mobile stars.",
    "blocks": "Happy Caly stacking colorful soft blocks.",
    "splash": "Happy Caly splashing in shallow tub with water drops.",
    "clap": "Happy Caly clapping hands together, five fingers visible.",
    "peek": "Happy Caly playing peek-a-boo behind small blanket.",
    "cuddle": "Happy Caly hugging soft teddy for cuddle time.",
    "lullaby": "Happy Caly with musical notes and moon, gentle lullaby.",
    "yum": "Happy Caly tasting spoon with yummy face.",
    "owie": "Soft caring expression with small bandage, kid-safe owie.",
    "blankie": "Happy Caly holding soft security blankie.",
    "potty": "Happy Caly beside friendly potty chair, kid-safe.",
    "bubbles": "Happy Caly blowing soap bubbles, five fingers on wand.",
    "sandbox": "Happy Caly playing in sandbox with bucket and shovel.",
    "truck": "Happy Caly beside bright toy dump truck.",
    "puzzle": "Happy Caly fitting puzzle piece into board.",
    "sticker": "Happy Caly holding shiny reward sticker star.",
    "wagon": "Happy Caly pulling little red wagon.",
    "cereal": "Happy Caly with bowl of cereal and spoon.",
    "yogurt": "Happy Caly holding small yogurt cup with spoon.",
    "tricycle": "Happy Caly beside colorful tricycle.",
    "science": "Happy Caly with beaker and magnifying glass, kid science.",
    "guitar": "Happy Caly strumming small acoustic guitar.",
    "soccer": "Happy Caly kicking soccer ball on grass.",
    "birthday": "Happy Caly with birthday cake and one candle.",
    "museum": "Happy Caly pointing at museum building with columns.",
    "camping": "Happy Caly beside small tent under stars.",
    "scooter": "Happy Caly riding kick scooter safely.",
    "tablet": "Happy Caly holding kid tablet with friendly app icon.",
    "spelling": "Happy Caly arranging letter tiles, no readable text.",
    "kite": "Happy Caly flying colorful kite in breeze.",
    "algebra": "Happy Caly with chalkboard showing simple equation shapes not readable text.",
    "presentation": "Happy Caly at small podium presenting with pointer.",
    "permission": "Happy Caly holding signed permission slip envelope.",
    "detention": "Calm serious expression at desk with clock, school detention kid-safe.",
    "orchestra": "Happy Caly holding violin in orchestra setting.",
    "robotics": "Happy Caly beside small friendly robot kit.",
    "podcast": "Happy Caly with microphone and headphones podcasting.",
    "charger": "Happy Caly plugging phone charger cable safely.",
    "earbuds": "Happy Caly holding wireless earbuds case.",
    "debate": "Happy Caly at debate podium with speech bubble shapes.",
    "volunteer": "Happy Caly holding volunteer badge and heart.",
    "mindfulness": "Calm peaceful smile with eyes closed, breathing leaf motif.",
    "syllabus": "Happy Caly holding school syllabus folder.",
    "textbook": "Happy Caly carrying stacked textbooks.",
    "yearbook": "Happy Caly holding school yearbook with photo shapes.",
    "drivers-license": "Happy Caly holding ID card shape, no readable text.",
    "internship": "Happy Caly with briefcase at office desk internship.",
    "scholarship": "Happy Caly holding diploma scroll with star award.",
    "credit-card": "Happy Caly holding payment card shape, no numbers.",
    "rideshare": "Happy Caly beside rideshare car with map pin.",
    "diploma": "Happy Caly holding rolled diploma with ribbon.",
    "tuition": "Happy Caly with tuition bill envelope and coin stack.",
    "roommate": "Happy Caly beside roommate in shared room bunk.",
    "budget": "Happy Caly with calculator and piggy bank budgeting.",
    "streaming": "Happy Caly with tablet showing play button triangle.",
    "social-media": "Happy Caly with phone showing heart and chat bubble icons.",
    "part-time": "Happy Caly in work apron with part-time schedule.",
    "parking": "Happy Caly beside car in parking spot with P sign.",
    "copay": "Happy Caly holding copay receipt and coin at clinic.",
    "gig-work": "Happy Caly with delivery bag gig work friendly.",
    "mortgage": "Happy Caly with house key and mortgage document envelope.",
    "retirement": "Happy Caly with nest egg piggy bank and calendar.",
    "taxes": "Happy Caly with tax folder and calculator.",
    "benefits": "Happy Caly holding employee benefits folder.",
    "pension": "Happy Caly with pension nest and clock toward future.",
    "warranty": "Happy Caly holding warranty shield badge.",
    "subscription": "Happy Caly with subscription box and renewal arrow.",
    "direct-deposit": "Happy Caly with bank deposit arrow into account icon.",
    "overtime": "Happy Caly with overtime clock showing extra hours.",
    "performance-review": "Happy Caly at review meeting with checklist.",
    "onboarding": "Happy Caly with welcome badge and orientation folder.",
    "hr": "Happy Caly at HR desk with friendly folder.",
    "contractor": "Happy Caly with hard hat and contractor toolbox.",
    "regulation": "Calm Caly modeling deep breath for regulation coaching.",
    "patience": "Happy patient smile with hourglass patience coaching.",
    "breathe": "Calm Caly with breathing arrows in and out.",
    "visual-schedule": "Happy Caly pointing at picture schedule board icons.",
    "celebrate": "Happy Caly with confetti celebrating effort.",
    "modeling": "Happy Caly demonstrating word gesture for modeling.",
    "scaffold": "Happy Caly offering gentle support hand scaffold coaching.",
    "prompt-wait": "Happy Caly with pause palm prompt and wait gesture.",
    "reinforcement": "Happy Caly giving thumbs up reinforcement star.",
}


def main() -> None:
    words = sys.argv[1:] if len(sys.argv) > 1 else ["sad", "all-done", "go", "wait", "home", "hug"]
    for word in words:
        action = ACTIONS.get(word, f"Happy Caly demonstrating the word {word}.")
        for band in BANDS:
            out = subprocess.check_output(
                [sys.executable, str(PROMPT_SCRIPT), band, word, action],
                text=True,
            ).strip()
            print(f"\n# {word}-{band}.png")
            print(out)


if __name__ == "__main__":
    main()
